# ------------------------------------------------------------------------------
# Install tmux from source


- name: Install dependencies for compiling and running
  ansible.builtin.apt:
    name: 
      - tmux
      - libevent-dev 
      - ncurses-dev
      - build-essential
      - bison
      - pkg-config
      - autoconf 
      - automake
      - pkg-config
    state: present
  become: true

- name: Get current version
  ansible.builtin.command: tmux -V
  register: tmux_version
  changed_when: false

- { name: "Debug", debug: {var: tmux_version.stdout_lines}, tags: [debug]}

- name: Clone source repo
  when: tmux_version.stdout != "tmux 3.2a"
  ansible.builtin.git:
    repo: https://github.com/tmux/tmux.git
    dest: /tmp/tmux
    version: "3.2"
    depth: 1
    force: false
  become: true

- name: Compile and install
  when: tmux_version.stdout != "tmux 3.2a"
  ansible.builtin.shell: |
    cd /tmp/tmux \
      && sh autogen.sh \
      && ./configure \
      && make \
      && make install
  become: true


# ------------------------------------------------------------------------------
# Place files and stuff


- name: Create necessary directories
  ansible.builtin.shell: |
    mkdir -p ~/.config/tmux
  args: {warn: false} 
  changed_when: false

- name: Place ~/.tmux.conf
  ansible.builtin.copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
    mode: u=rw,g=r,o=r
    force: true

- name: Place ~/.config/tmux/pre-tpm.sh
  ansible.builtin.copy:
    src: pre-tpm.sh
    dest: ~/.config/tmux/pre-tpm.sh
    mode: u=rwx,g=r,o=r
    force: true

- name: Place ~/.config/tmux/post-tpm.sh
  ansible.builtin.copy:
    src: post-tpm.sh
    dest: ~/.config/tmux/post-tpm.sh
    mode: u=rwx,g=r,o=r
    force: true

- name: Place ~/.config/tmux/toggle-mouse.sh
  ansible.builtin.copy:
    src: toggle-mouse.sh
    dest: ~/.config/tmux/toggle-mouse.sh
    mode: u=rwx,g=r,o=r
    force: true

- name: Place ~/.config/tmux/uptime.sh
  ansible.builtin.copy:
    src: uptime.sh
    dest: ~/.config/tmux/uptime.sh
    mode: u=rwx,g=r,o=r
    force: true


# ------------------------------------------------------------------------------


- name: Clone tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: "HEAD"
    depth: 1
    force: false

- name: Install plugins
  shell: bash -c "~/.tmux/plugins/tpm/bin/install_plugins"
  register: task
  changed_when: '"download success" in task.stdout'


# ------------------------------------------------------------------------------
